[package]
name = "reebundle"
version = "0.1.2"
edition = "2021"

[lib]
name = "reebundle"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.18.0", features = ["extension-module"] }
numpy = "0.18.0"

[features]
extension-module = ["pyo3/extension-module"]
default = ["extension-module"] 